# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Juan Pablo Gonzalez
email: me@juanpablogonzalez.info
description: > # this means to ignore newlines until "baseurl:"
 Juan Pablo Gonzalez Personal
baseurl: "" # the subpath of your site, e.g. /blog
url: "juanpablogonzalez.info" # the base hostname & protocol for your site
twitter_username: JPG_MX
github_username:  JPGMX

# Build settings
markdown: kramdown
